### ISSUE TITLE
User login form v1

### ISSUE THREAD

**Issue by tomliangg** [iparkmse/ipark-web#1]
## :loudspeaker: Feature statements  
- Implement a user login form UI

## :ticket: Accepted criteria
- username field
- password field (text type should be password)
- login button
- states should be already updated before login button is pressed
- console log the states when login button is pressed
- form should be cleared

## :bulb: Additional description
- just a plain UI. Linkup work with backend will be done in v2
- UI Mockup
![LogIn.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c37e15fa8675f00131fff7a/125516c66e82c728ace21e0d46c49b9d0a8cc1e5cdf9ad4cae58f3806b1c65262a52f0792987bb78bc1a2a04095f4fa9400c5a4dadf98839baa47e21d40854b088270a36d43703adb0881eba04ba228d4c8cb3b98d4ac2fa70.png)
![Parking_Status.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c37e15fa8675f00131fff7a/125516c66e82c728ace21e0d46d89588288b8daeb0daab42b048e3d665043761260ea62864c7b96aea412d525d561ca4410b5745a9af892aa3b76875830d0becc3714d36976345f3e5db55ea43a82a994e8dbcbd8f49c0ea3b26ee8e8a47381e1755.png)
![SignUp.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c37e15fa8675f00131fff7a/125516c66e82c728ace21e0d46db9d9d2db793ebc3abaf51ab57f5973d047d317c07f57822dce170ef4123500a094ead44590b41f5a8892ab4aa2e32db025fb28c341521842f1bbeb98b15be04bf20894986bfb98f4bc8ed2f68.png)

**Comment by RamitaTr** [comment]
Pull requested: https://github.com/iparkmse/ipark-web/pull/8
