### ISSUE TITLE
parking status UI v1

### ISSUE THREAD

**Issue by tomliangg** [iparkmse/ipark-web#2]
## :loudspeaker: Feature/Story statements  
- Implement a table component that can be passed data (array of 10 objects) props and display the data  

## :ticket: Accepted criteria  
- Table component should be able to  display parking lot status data in 10 rows x 2 columns  

## :bulb: Additional information  
- n/a

**Comment by RamitaTr** [comment]
Pull requested: https://github.com/iparkmse/ipark-web/pull/7

**Comment by RamitaTr** [comment]
Pul requested: https://github.com/iparkmse/ipark-web/pull/7
